# This tells pytest to treat the project root as the Python path: pytest.ini
[pytest]
pythonpath = .
markers=
    smoke:
    sanaity:
    regression:
    skip: skip a test for any reason
    xfail: mark a test as expected to fail
    flaky: mark a test as flaky and enable retry
    dependency: mark a test as dependent on another test
    skipif: skip a test if a condition is met
    parametrize: parameterize a test with multiple inputs
addopts = --html=report/report.html --self-contained-html
