# This tells pytest to treat the project root as the Python path: pytest.ini
[pytest]
pythonpath = .
markers=
    smoke:
    sanaity:
    regression:
addopts = --html=report/report.html --self-contained-html
